spring.application.name=InventoryManagement
server.port=${PORT}

# REMOVE the datasource lines. Spring will use SPRING_DATASOURCE_* env vars you set.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
